name: build_and_tests
on:
  push:
    paths-ignore:
      - 'bin/**'
      - 'images/**'
      - 'share/**'
      - '.github/**'
      - '**.md'
      - '.gitignore'
    tags:
      - v*
    branches:
      - master
      - main
      - feature/**
      - bugfix/**
jobs:
  build:
    name: Build
    strategy:
      matrix:
        go-version: [1.20.x, 1.21.x, 1.22.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Build TinkoffInvest
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build ./cmd/balancer/main.go

      - name: Test All
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go test -v ./...